### ISSUE TITLE
LCD all white

### ISSUE THREAD

**Issue by cuvoodoo** [ataradov/open-5012h#1]
the very first time I flashed the firmware, the LCD worked and showed the oscilloscope screen.
the second time I powered the device (and further on), the LCD is only white, at the maximum brightness.
re-flashing the firmware, even after a chip erase, did not fix the issue.
I tried to change the rectangle color and reduce the brightness in lcd_init, but this did not change anything.
I guess there is something missing during the initialization, but I am not familiar with the ST7789.
Do you have any glue what the issue could be?

edit: the firmware seems to be running fine else (at least is is not stuck, and periodically calls lcd_data_write)

**Comment by ataradov** [comment]
The first thing I would do is to add a whole lot more nops in the  lcd_data_write(). The LCD is technically overclocked, so it is possible that your particular sample can't take it.

**Comment by cuvoodoo** [comment]
good guess. with 200 additional NOPs I can see the display.
the refresh rate drops to 1 Hz though (still under the timer overflow limit).
the drawing gets more and more incorrect with time (the data is still displayed, but the pixel values are wrong).
this issue increases the less NOPs there are.
I will look into making it more reliable, maybe using interrupts and double buffering if necessary.

**Comment by ataradov** [comment]
You should not need a lot of nops. Just adding a few would bring the timings into the spec.

If adding 4-5 nops into each group does not help, something else is wrong.

**Comment by cuvoodoo** [comment]
then something else is wrong. the minimum I need is the following (each loop iteration is equivalent to 2 NOPs).

```
  GPIOE->BOP = (~value << 16) | value;
  for (volatile uint8_t i = 0; i < 10; i++);
  HAL_GPIO_LCD_WR_clr();
  for (volatile uint8_t i = 0; i < 65; i++);
  HAL_GPIO_LCD_WR_set();
  for (volatile uint8_t i = 0; i < 10; i++);
```
before that nothing gets drawn.
after that I see a refresh, but the drawing is still incorrect (as show in picture)

![h5012-min-display](https://user-images.githubusercontent.com/35878664/98108315-07d40900-1e9c-11eb-90ed-0d419ba23532.jpg)

**Comment by ataradov** [comment]
In theory the first loop is what matters the most. That is what defines data setup time before the write strobe.

The one you have at 65 is just a write strobe, and if it does not work at all when you set lower number, then this is the first thing to look at. 

The best thing I can suggest is to look at the signals going to the LCD using a different scope and see if they look ok.

**Comment by cuvoodoo** [comment]
I took a look a it again, and after some trials I found out the code wasn't the issue.
I cleaned the LCD solder pads (where the flex cable is connected to the board), and now it works perfectly.
