### ISSUE TITLE
Measurements in the right side of the bottom bar do not appear to work

### ISSUE THREAD

**Issue by petrenn** [ataradov/open-5012h#6]
Played using a 100 KHz waveform and changing the frequency or the amplitude don't seem to affect the measurements [on](url) the right side of the bar. Is it possible to add a frequency measurement
![Capture](https://user-images.githubusercontent.com/95179384/143775101-ce76a294-7af2-4ce3-80e9-e27ef8351838.PNG)
?

**Comment by ataradov** [comment]
There are no measurements. Those numbers are trigger level and offset settings.

It would not be too hard to add measurements, but I don't have time to spend on this firmware. I have no real interest in a project.

**Comment by petrenn** [comment]
I totally understand where you stand from.
My friend Zibo removed the check for timer thing and seems ok but he doesn’t know much about this processor so he can’t add them unfortunately so I’m stuck. 

Those measurements would complete this little scope if you could add them especially if they’re easy to add (for you)and I’m sure they would make a lot of people happy. 
I’m just dreading to swap the old processor back especially after inadvertently heated the display too much and caused fading in the right top corner.

Please, Alex ?

Nick-

**Comment by ataradov** [comment]
I'll work on it, but I can't promise anything. I need to see how hard it actually is to implement.

**Comment by ataradov** [comment]
I've implemented the measurements in the latest commit. I did minimal testing, but it seems to work quite well.

MODE button toggles display of measurements and trigger parameters.

Frequency measurements are performed at the trigger level, so the scope must be triggered.

**Comment by petrenn** [comment]
Alex, the changes seem to work well. Frequency measurement is bang-on and so is the voltage (if calibrated properly). Many thanks for taking the time to add these.
